### ISSUE TITLE
Question about using "use_undistort" in Nerfies dataset

### ISSUE THREAD

**Issue by zhanghe3z** [KAIR-BAIR/dycheck#5]
Great work! I am currently using the Nerfies dataset for my experiments. I was wondering if it is possible to set the "use_undistort" parameter to True when using the Nerfies datase. I would like to try this feature out, but I am unsure if it would affect the performance. Thank you!

**Comment by hangg7** [comment]
Hi! `use_undistort` should just work out-of-the-box, feel free to play with it. Under the hood, it will undistort the images using opencv and use those data for traiing and testing instead. The caveat is that it will introduce "masks" to the images due to the perspective warping, our code take care of that by not supervising (and evaluating) those pixels.

Feel free to reopen and follow up on any related questions!
